// Mis operaciones sincronizadas, versiones, vista previa, descargar/compartir; carga masiva y firma masiva.
const { _electron: electron } = require('playwright'); const path = require('path'); const fs = require('fs'); const os = require('os');
const ok = (c, m) => { if (!c) throw new Error('FALLÓ: ' + m); console.log('  ✔ ' + m); };
(async () => {
  const userData = fs.mkdtempSync(path.join(os.tmpdir(), 'pfop-'));
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'pfbk-'));
  const docs = [];
  for (let i = 1; i <= 7; i++) { const f = path.join(tmp, `Contrato ${i}.pdf`); const b = fs.readFileSync(path.resolve(__dirname, 'fixtures', 'contrato_prueba.pdf')); fs.writeFileSync(f, Buffer.concat([b, Buffer.from(`\n%${i}\n`)])); docs.push(f); }
  fs.copyFileSync(docs[0], path.join(tmp, 'Copia.pdf')); docs.push(path.join(tmp, 'Copia.pdf'));
  fs.writeFileSync(path.join(tmp, 'nota.txt'), 'x'); docs.push(path.join(tmp, 'nota.txt'));
  docs.push(path.resolve(__dirname, 'fixtures', 'contrato.docx'));
  const app = await electron.launch({ args: ['.', '--no-sandbox', `--user-data-dir=${userData}`], cwd: path.join(__dirname, '..'), env: { ...process.env, PF_MOCK: '1', PF_MOCK_LOGGED: '1' } });
  const w = await app.firstWindow(); const errs = global.__errs = []; w.on('pageerror', (e) => errs.push('PAGE: ' + e.message)); w.on('console', (m) => m.type() === 'error' && errs.push(m.text()));
  await w.setViewportSize({ width: 1440, height: 900 }); await w.waitForSelector('.hub-card');
  const sleep = (ms) => w.waitForTimeout(ms);
  await app.evaluate(({ dialog }, d) => { dialog.showSaveDialog = async (_w, o) => ({ canceled: false, filePath: d + '/' + String(o.defaultPath).split(/[\\/]/).pop() }); dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [d] }); }, tmp);

  console.log('Mis operaciones');
  await w.click('.hub-card[data-act="ops"]'); await w.waitForSelector('#opPhone');
  ok(/teléfono con el que te registraste/.test(await w.textContent('#modalCard')), 'pide el teléfono de la cuenta la primera vez');
  await w.fill('#opPhone', '9 8727 6858'); await w.click('#mOk');
  await w.waitForFunction(() => document.querySelectorAll('.ops-row').length >= 10, null, { timeout: 30000 });
  const n = await w.locator('.ops-row').count(); ok(n === 15, `sincroniza todas las operaciones, también las de más de un año (${n})`);
  await w.waitForFunction(() => !window.Operaciones._ops.prefetching && window.Operaciones._ops.items.every((x) => x.status), null, { timeout: 60000 });
  const f = await w.evaluate(() => Object.fromEntries([...document.querySelectorAll('.ops-f')].map((b) => [b.dataset.f, Number(b.querySelector('b').textContent)])));
  console.log('    filtros:', JSON.stringify(f));
  ok(f.notary > 0 && f.signed > 0 && f.pending > 0 && f.all === 15, 'filtros con conteos (firmadas, legalizadas, en firma)');
  await w.click('.ops-f[data-f="notary"]'); await sleep(200);
  ok(await w.locator('.ops-row').count() === f.notary, 'filtrar legalizadas/protocolizadas');
  await w.click('.ops-f[data-f="all"]'); await w.fill('#opsQ', 'mandato'); await sleep(200);
  ok(await w.locator('.ops-row').count() >= 1 && (await w.locator('.ops-row').allTextContents()).every((t) => /Mandato/i.test(t)), 'buscar por nombre');
  await w.fill('#opsQ', ''); await sleep(100);
  await w.click('.ops-row[data-op="20900"]'); await w.waitForSelector('.opd-steps');
  const steps = await w.evaluate(() => [...document.querySelectorAll('.opd-step')].map((s) => s.textContent.replace(/\s+/g, ' ').trim()));
  console.log('    etapas:', steps.join(' → '));
  ok(steps.length === 3 && /Enviado/.test(steps[0]) && /Legalizado/.test(steps[2]), 'etapas Enviado → Firmado → Legalizado (solo estado)');
  await w.waitForSelector('#opdCanvas canvas', { timeout: 20000 }); ok(true, 'vista previa del documento (servicio getById)');
  ok(/2 de 2 firmaron/.test(await w.textContent('.opd-side h4')), 'firmantes y estado');
  await w.screenshot({ path: path.resolve(__dirname, 'o1-operacion.png') });
  ok(!(await w.$('#opdAll')) && !(await w.$('[data-v]')), 'sin descargas por versión: un solo documento por operación');
  await w.click('#opdDl'); await sleep(900); console.log('    toast:', await w.textContent('#toast'), fs.readdirSync(tmp).join(','));
  ok(fs.readdirSync(tmp).some((x) => /^20900 - Contrato de arrendamiento\.pdf$/.test(x)), 'descargar el documento con el nombre que entrega getById');
  await w.click('.ops-row[data-op="20886"]'); await w.waitForSelector('.opd-sig-acts');
  ok(await w.locator('.opd-sig-acts').count() === 1, 'operación en firma: acciones para el firmante pendiente');
  await w.click('.opd-sig-acts [data-mail]'); await w.waitForSelector('#mOk:has-text("Enviar")'); ok(/por correo/.test(await w.textContent('#modalCard')), 'reenviar enlace pide confirmación'); await w.click('#mCancel');

  console.log('Carga masiva');
  await w.click('#opsBulk'); await w.waitForSelector('#bkDrop');
  await w.evaluate((p) => window.pf.bulkAdd(p), docs);
  await w.waitForFunction(() => window.Masiva._bk.st.items.length === 10 && window.Masiva._bk.st.items.every((x) => !['queued', 'converting', 'uploading', 'analyzing'].includes(x.status)), null, { timeout: 120000 });
  const st = await w.evaluate(() => window.Masiva._bk.st.items.map((x) => x.status + ':' + x.name));
  console.log('   ', st.join(' | '));
  ok(st.filter((x) => x.startsWith('needs_data')).length === 8, '8 analizados (incluido el Word convertido); avisa que faltan correo y teléfono');
  ok(st.some((x) => /skipped:Copia/.test(x)) && st.some((x) => /skipped:nota/.test(x)), 'omite duplicados y formatos no admitidos');
  const maxPar = await w.evaluate(() => window.__maxPar || 0); void maxPar;
  await w.screenshot({ path: path.resolve(__dirname, 'o2-masiva.png') });
  // editar firmantes de uno
  await w.click('.bk-row.needs_data >> nth=0 >> [data-a="edit"]'); await w.waitForSelector('.bk-sigrow');
  await w.fill('.bk-sigrow >> nth=0 >> [data-k="email"]', 'juan@correo.cl'); await w.fill('.bk-sigrow >> nth=0 >> [data-k="phone"]', '+56911111111');
  await w.fill('.bk-sigrow >> nth=1 >> [data-k="email"]', 'maria@correo.cl'); await w.fill('.bk-sigrow >> nth=1 >> [data-k="phone"]', '+56922222222');
  await w.click('#mOk'); await sleep(400);
  ok(await w.evaluate(() => window.Masiva._bk.st.items.filter((x) => x.status === 'ready').length) === 1, 'editar firmantes: ese documento queda listo');
  await w.click('.bk-row.ready >> [data-a="edit"]'); await w.waitForSelector('.bk-sigrow'); await w.click('#bkAll'); await sleep(500);
  ok(await w.evaluate(() => window.Masiva._bk.st.items.filter((x) => x.status === 'ready').length) === 8, '«Usar en todos»: 8 listos');
  await w.click('.bk-row.ready >> nth=1 >> input[type=checkbox]'); await sleep(300);
  await w.click('[data-a="send"]'); await w.waitForSelector('#bkPay');
  ok(/descuenta saldo/.test(await w.textContent('#modalCard')) && /Enviar 7/.test(await w.textContent('#mOk')), 'una sola confirmación, avisa el cobro (7 seleccionados)');
  await w.fill('#bkPay', 'pagos@empresa.cl'); await w.click('#mOk');
  await w.waitForFunction(() => window.Masiva._bk.st.items.filter((x) => x.status === 'sent').length === 7 && !window.Masiva._bk.st.sending, null, { timeout: 60000 });
  ok(true, '7 enviados a firmar, de a uno');
  ok(await w.evaluate(() => window.Masiva._bk.st.items.filter((x) => x.status === 'ready').length) === 1, 'el desmarcado queda listo, sin enviar');
  await w.evaluate((p) => window.pf.bulkAdd([p]), docs[2]); await sleep(800);
  ok(await w.evaluate(() => window.Masiva._bk.st.items.at(-1).dupSent === true), 'avisa si un archivo ya se envió antes');
  await w.click('.bk-row.sent >> nth=0 >> [data-a="seeop"]'); await w.waitForSelector('.opd-steps', { timeout: 20000 });
  ok(true, 'del envío a su operación en Mis operaciones');

  console.log('Firma masiva con certificado');
  await w.evaluate(() => window.Masiva.open('cds')); await w.waitForSelector('#cdsRut');
  await w.fill('#cdsRut', '12.345.678-5'); await w.click('#cdsList'); await w.waitForSelector('.cds-op');
  ok(await w.locator('.cds-op').count() === 3, 'lista las operaciones pendientes');
  await w.locator('.cds-op input >> nth=2').uncheck(); await sleep(100);
  await w.fill('#cdsKey', 'clave-secreta'); await w.click('#cdsAsk'); await w.waitForSelector('#cdsCode');
  await w.fill('#cdsCode', '123456'); await w.click('#cdsSign'); await w.waitForSelector('.cds-res');
  ok(/2 de 2/.test(await w.textContent('.cds-res')), 'firma las 2 elegidas con un solo código');
  ok(await w.evaluate(() => window.Masiva._cds.clave === ''), 'la clave del certificado se borra al terminar');
  const disk = fs.readFileSync(path.join(userData, 'portalfirma.json'), 'utf8');
  ok(!disk.includes('clave-secreta'), 'la clave nunca se guarda en disco');
  await w.screenshot({ path: path.resolve(__dirname, 'o3-cds.png') });
  const bad = errs.filter((e) => !/Warning|deprecated|font|TT:/i.test(e)); console.log('errores:', bad); if (bad.length) process.exitCode = 1;
  await w.evaluate(() => window.pf.closeNow()).catch(() => {}); await app.close().catch(() => {}); process.exit(process.exitCode || 0);
})().catch((e) => { console.error('FAIL', e); console.error(global.__errs); process.exit(1); });
